name: Brakeman

on:
  workflow_call:
    secrets:
      bundle_token:
        required: true

jobs:
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up mise
        uses: jdx/mise-action@v2
      - name: Install runtimes
        run: mise install
      - name: Install Ruby dependencies
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.bundle_token }}
        run: bundle install --jobs 4 --retry 3
      - name: Brakeman
        uses: reviewdog/action-brakeman@v2
        with:
          github_token: ${{ secrets.bundle_token }}
          reporter: github-pr-review
