name: Tests

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      use_node:
        type: boolean
        required: false
        default: false
    secrets:
      master_key:
        required: true
      bundle_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MISE_EXPERIMENTAL: true
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: ${{ inputs.app_name }}_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:alpine
        ports: ["6379:6379"]
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up mise
        uses: jdx/mise-action@v3
      - name: Run CI task
        timeout-minutes: 15
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.bundle_token }}
          NODE_OPTIONS: --openssl-legacy-provider
          REDIS_URL: redis://localhost:6379/0
          RAILS_MASTER_KEY: ${{ secrets.master_key }}
        run: mise run ci
      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: /home/runner/work/${{ inputs.app_name }}/${{ inputs.app_name }}/tmp/screenshots/
