name: Deploy app

on:
  workflow_call:
    secrets:
      bundle_token:
        required: true
      shopify_cli_token:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      MISE_EXPERIMENTAL: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up mise
        uses: jdx/mise-action@v3
      - name: Deploy
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.bundle_token }}
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.shopify_cli_token }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
        run: mise run shopify:deploy
