name: ERB Lint

on:
  workflow_call:
    secrets:
      bundle_token:
        required: true

jobs:
  erb-lint:
    runs-on: ubuntu-latest
    env:
      MISE_EXPERIMENTAL: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up mise
        uses: jdx/mise-action@v3
      - name: Run ERB lint task
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.bundle_token }}
        run: mise run lint:erb
