name: ERB Lint

on:
  workflow_call:
    secrets:
      bundle_token:
        required: true

jobs:
  erb-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up mise
        uses: jdx/mise-action@v2
      - name: Install runtimes
        run: mise install
      - name: Install Ruby dependencies
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.bundle_token }}
        run: bundle install --jobs 4 --retry 3
      - name: erb-lint
        uses: tk0miya/action-erblint@v1
        with:
          github_token: ${{ secrets.bundle_token }}
          reporter: github-pr-review
          use_bundler: true
