name: Prettier

on:
  workflow_call:
    secrets:
      bundle_token:
        required: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    env:
      MISE_EXPERIMENTAL: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set up mise
        uses: jdx/mise-action@v3
      - name: Run formatter task
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.bundle_token }}
        run: mise run format:write
